authConfig:
    serviceRegistry:
        username: serviceregistry
        password: '12345678'

api:
    security:
        token:
            secret: 123456
            expiration: 7200000 # 2 horas em milissegundos

eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://${authConfig.serviceRegistry.username}:${authConfig.serviceRegistry.password}@${eureka.instance.hostname}:8761/eureka/
