authConfig:
    serviceRegistry:
        username: serviceregistry
        password: '12345678'

eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://${authConfig.serviceRegistry.username}:${authConfig.serviceRegistry.password}@${eureka.instance.hostname}:8761/eureka/
